name: apex_collections
description: A high-performance, immutable collection library for Dart, aiming to surpass existing solutions.
version: 0.0.1 # Start with pre-release version
repository: https://github.com/your_github_username/apex_collections # TODO: Update with actual URL

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  meta: ^1.12.0 # For @immutable etc.
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0 # Using flutter_lints for stricter rules
  test: ^1.24.0
  benchmark_harness: ^2.2.0 # For performance benchmarking
  fast_immutable_collections: ^10.2.1 # Baseline for comparison
